(function() {var implementors = {};
implementors['gcrypt'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a> for <a class='struct' href='gcrypt/mpi/integer/struct.Integer.html' title='gcrypt::mpi::integer::Integer'>Integer</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='gcrypt/mpi/integer/struct.Integer.html' title='gcrypt::mpi::integer::Integer'>Integer</a>&gt; for &amp;'a <a class='struct' href='gcrypt/mpi/integer/struct.Integer.html' title='gcrypt::mpi::integer::Integer'>Integer</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;&amp;'a <a class='struct' href='gcrypt/mpi/integer/struct.Integer.html' title='gcrypt::mpi::integer::Integer'>Integer</a>&gt; for <a class='struct' href='gcrypt/mpi/integer/struct.Integer.html' title='gcrypt::mpi::integer::Integer'>Integer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;&amp;'a <a href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.String.html' title='collections::string::String'>String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
